spring.application.name=banking-transactions-api
# ===================================================================
# CONFIGURACIÓN DEL SERVIDOR
# ===================================================================
server.port=8080

# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (H2 en Memoria)
# ===================================================================
spring.datasource.url=jdbc:h2:mem:bankingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'update' crea las tablas automáticamente en el arranque si no existen
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola para ver qué está pasando por debajo
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# CONSOLA WEB DE H2 (Para revisar las tablas en el navegador)
# ===================================================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Desactiva la protección de frames de Spring Security para poder ver la consola de H2 si aplica
spring.h2.console.settings.web-allow-others=true
